import type { Metadata } from "next";
import "./globals.css";
import { Cabin, Inter, Noto_Sans, Roboto } from "next/font/google";
import { ReactNode } from "react";
import { ThemeProvider } from "@/provider/ThemeProvider";
import ApolloGqlProvider from "@/provider/ApolloProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// const cabin = Cabin({
//   subsets: ["latin"],
//   variable: "--font-sans",
// });
const inter = Roboto({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["100", "300", "400", "500", "700", "900"],
});
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <ApolloGqlProvider>{children}</ApolloGqlProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
