import type { Metadata } from "next";
import "primereact/resources/themes/md-light-deeppurple/theme.css";
import "primeicons/primeicons.css";
import "./globals.css";
import { Cabin } from "next/font/google";
import { ReactNode } from "react";
import { ThemeProvider } from "@/provider/ThemeProvider";
import ApolloGqlProvider from "@/provider/ApolloProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const cabin = Cabin({
  subsets: ["latin"],
  variable: "--font-sans",
});
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={cabin.className}>
        <ThemeProvider>
          <ApolloGqlProvider>{children}</ApolloGqlProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
