export const AppConfig = {
  COMPANY_TYPE: [
    { label: "Automobiles", value: 1 },
    { label: "Agriculture based", value: 2 },
    { label: "Banking", value: 3 },
    { label: "BPO", value: 4 },
    { label: "Capital goods", value: 5 },
    { label: "Telecom", value: 6 },
    { label: "IT", value: 7 },
    { label: "Retail", value: 8 },
    { label: "Real estate", value: 9 },
    { label: "Consumer Durable", value: 10 },
    { label: "FMGC", value: 11 },
    { label: "NBFC", value: 12 },
    { label: "Marketing/Advertisement", value: 13 },
    { label: "Parma", value: 14 },
    { label: "Media", value: 15 },
    { label: "Manufacturing", value: 16 },
    { label: "Trading", value: 17 },
    { label: "Export", value: 18 },
    { label: "Transport", value: 19 },
    { label: "Others", value: 20 },
  ],
  ACCESS: [
    { label: "None", value: 0, name: "NONE" },
    { label: "Employee", value: 5, name: "EMPLOYEE" },
    { label: "Payroll", value: 10, name: "PAYROLL" },
    { label: "Employee Credential", value: 15, name: "EMPLOYEE_CREDENTIAL" },
  ],
  WORKING_MODE: [
    { label: "ONSITE", value: "ONSITE", count: 1 },
    { label: "HYBRID", value: "HYBRID", count: 2 },
    { label: "REMOTE", value: "REMOTE", count: 3 },
    { label: "OTHER", value: "OTHER", count: 4 },
  ],
};
