export const AppConfig = {
  NODE_GQL_URL: "http://localhost:4000/graphql",
  CREDENTIAL: "credential",
  ORGANIZATION_TYPE: [
    { label: "Automobiles", value: 1 },
    { label: "Agriculture based", value: 2 },
    { label: "Banking", value: 3 },
    { label: "BPO", value: 4 },
    { label: "Capital goods", value: 5 },
    { label: "Telecom", value: 6 },
    { label: "IT", value: 7 },
    { label: "Retail", value: 8 },
    { label: "Real estate", value: 9 },
    { label: "Consumer Durable", value: 10 },
    { label: "FMGC", value: 11 },
    { label: "NBFC", value: 12 },
    { label: "Marketing/Adertisement", value: 13 },
    { label: "Pharma", value: 14 },
    { label: "Media", value: 15 },
    { label: "Manufacturing", value: 16 },
    { label: "Trading", value: 17 },
    { label: "Export", value: 18 },
    { label: "Transport", value: 19 },
    { label: "Others", value: 20 },
  ],
};
